name: hytribe
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+4

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.2
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.1
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  flutter_gemini: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_media_store: ^1.3.1
  flutter_signin_button: ^2.0.0
  get: ^4.6.5
  google_sign_in: ^6.2.2
  marquee: ^2.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1
flutter_icons:
  image_path: "icons/logo-hyt.png"
  android: true
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
